NAME: 配置信息


#元素高亮显示配置
HightLight: 1
#1:高亮显示
#其它:忽略高亮


CONFIG:
    Cookies: #cook信息
        USED: true
        LoginCookies:
            manager_autologin: "true"
            manager_bid: "1428708010"
            manager_mid: "1196432510"
            manager_sid: "0"
            manager_sign: "c79869ecfb42fe977e504c22dae4ee1d"

        BossLoginCookies: {"name":"UserSession","value":"5b5ae93a272d7"} #boss,浏览器关闭session过期

    #浏览器 <Chrome 或 Firefox>
    Browser:  Chrome

    Base_Url: http://manage.acewill.net

    # 自定义全局变量
    Custom_Var:
        "%BLANK%": "self.clear_input_text(*loc)"
        "%NONE%": "None"
        "%RND%": "self.send_keys(genrandomstr({}).format(text), *loc)"
        "%timestamp%": "int(time.time())"

# 发送报告设置；DING 企业微信 True推送；False不推送；EMAIL：True发送邮件，False不发送
MESSAGE:
    DING: true
    EMAIL: false
    # 这里需要注意MSG中的{}位置；这个是format会将测试结果，参数化进来。
    TOKEN: "2c412f54-b815-45c5-b928-8fec114d1ea9"
    MSG: "Pro商家后台UI自动化测试执行【已完成】:\n{}\n测试报告:http://60.205.217.8:5004/pos/pro_manage/reports"

REPORT:
    title: "Pro商家后台UI自动化测试"
    description: "详细用例测试结果"
    tester: "welife"


#发送测试报告,邮件配置
EMAIL:
    Smtp_Server: smtp.exmail.qq.com
    Smtp_Sender: xxxxx.bj@acewill.cn
    Password: xxxxxxsssss
    Msg_Title: 线上商家后台-UI自动化测试结果
    #Receivers: ['lengyaohui@163.com']  #收件人
    Receivers: ['xxxxx@163.com'] #收件人
    From: 自动化测试系统
    To: 测试组

#REPLAY：Time元素回放时间(毫秒)
#CASE：Retry用例失败重试次数
RUNING: 
    REPLAY: 
        Time: 500
    CASE:
        Retry: 1

