NAME: 配置信息


#元素高亮显示配置
HightLight: 1
#1:高亮显示
#其它:忽略高亮


CONFIG:
    Cookies: #cook信息
        LoginCookies: {
               "manager_autologin":"true",
               "manager_bid":"1428708010",
               "manager_mid":"1196432510",
               "manager_sid":"0",
               "manager_sign":"c79869ecfb42fe977e504c22dae4ee1d"}

        BossLoginCookies: {"name":"UserSession","value":"5b5ae93a272d7"} #boss,浏览器关闭session过期

    #浏览器 <Chrome 或 Firefox>
    Browser:  Chrome

    Base_Url: http://manage.acewill.net

    Custom_Var:

        "%BLANK%": "self.clear_input_text(*loc)"
        "%NONE%": "None"
        "%RND%": "self.send_keys(genrandomstr({}).format(text), *loc)"
        "%timestamp%": "int(time.time())"

#发送测试报告,邮件配置
EMAIL:
    Smtp_Server: smtp.exmail.qq.com
    Smtp_Sender: lengyaohui.bj@acewill.cn
    Password: YHleng870120!
    Msg_Title: 线上商家后台-UI自动化测试结果
    #Receivers: ['lengyaohui@163.com']  #收件人
    Receivers: ['lengyaohui@163.com','yechangchun.bj@acewill.cn','wangchaoying.bj@acewill.cn','lilong.bj@acewill.cn','wangyan.bj@acewill.cn','cch@acewill.cn','gzx@acewill.cn','huxl@acewill.cn','jtt@acewill.cn','maming@acewill.cn'] #收件人
    From: 自动化测试系统
    To: 微生活测试组


RUNING: #case执行配置
    REPLAY: #元素回放配置
        Time: 500 #回放时间为毫秒

    DESCPTION: N不执行，Y执行
    CHARGE: #消费模块
        Flag: {"testCase1":{"Flag":"N","desc":"实体卡开卡"},
               "testCase2":{"Flag":"N","desc":"积分消费"},
               "testCase3":{"Flag":"N","desc":"储值消费"},
               "testCase4":{"Flag":"Y","desc":"券消费"},
               "testCase5":{"Flag":"N","desc":"实体卡绑卡"},
               "testCase6":{"Flag":"N","desc":"次卡开卡"}}

